/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://ag5tjxwyr5hjdizjs7idmvxvzy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ygggfvvor5g3nkz7kuitydzc7m",
    "aws_user_files_s3_bucket": "bucket145619-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
