/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:63a3a51e-5f6c-4e5c-b1f2-3f0fabb134f5",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YBVEAAEkr",
    "aws_user_pools_web_client_id": "2k3lslhmpcvbbocd3sa2g8gfkc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ag5tjxwyr5hjdizjs7idmvxvzy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ygggfvvor5g3nkz7kuitydzc7m"
};


export default awsmobile;
